DELETE FROM KOLONE_U_STRANOM_KLJUCU
DELETE FROM STRANI_KLJUC
DELETE FROM ATRIBUTI
DELETE FROM TABELE
delete from struktura_podsistema
DELETE from podsistem
insert into podsistem values ('PSW2018', 'PSW2018', 'S')
insert into podsistem values ('PRIMER', 'PRIMER', 'S')
insert into struktura_podsistema values ('PSW2018', 'PRIMER')
insert into TABELE values ('PRIMER', 'DRZ', 'Drzava')
insert into ATRIBUTI values ('PRIMER', 'DRZ', 'DRZ_ID', 'Oznaka', 'char', 1, 3, 0, 1)
insert into ATRIBUTI values ('PRIMER', 'DRZ', 'DRZ_ID_GG', 'Drzava glavni grad', 'char', 0, 3, 0, 0)
insert into ATRIBUTI values ('PRIMER', 'DRZ', 'NM_PB', 'Post. broj', 'char', 0, 5, 0, 0)
insert into ATRIBUTI values ('PRIMER', 'DRZ', 'DRZ_NAZIV', 'Naziv', 'varchar', 1, 128, 0, 0)
insert into TABELE values ('PRIMER', 'STU', 'Student')
insert into ATRIBUTI values ('PRIMER', 'STU', 'STU_INDEKS', 'Indeks', 'varchar', 1, 15, 0, 1)
insert into ATRIBUTI values ('PRIMER', 'STU', 'STU_DRZSTAN', 'Drzava stanovanja', 'char', 0, 3, 0, 0)
insert into ATRIBUTI values ('PRIMER', 'STU', 'STU_MESTOSTAN', 'Mesto stanovanja', 'char', 0, 5, 0, 0)
insert into ATRIBUTI values ('PRIMER', 'STU', 'STU_DRZRODJ', 'Drzava rodjenja', 'char', 0, 3, 0, 0)
insert into ATRIBUTI values ('PRIMER', 'STU', 'STU_MESTORODJ', 'Mesto rodjenja', 'char', 0, 5, 0, 0)
insert into ATRIBUTI values ('PRIMER', 'STU', 'STU_DATE', 'Datum rodjenja', 'datetime', 1, 0, 0, 0)
insert into ATRIBUTI values ('PRIMER', 'STU', 'STU_IME', 'Ime', 'varchar', 1, 64, 0, 0)
insert into ATRIBUTI values ('PRIMER', 'STU', 'STU_PREZIME', 'Prezime', 'varchar', 1, 64, 0, 0)
insert into TABELE values ('PRIMER', 'NM', 'Naseljeno mesto')
insert into ATRIBUTI values ('PRIMER', 'NM', 'DRZ_ID', 'Oznaka', 'char', 1, 3, 0, 1)
insert into ATRIBUTI values ('PRIMER', 'NM', 'NM_PB', 'Post. broj', 'char', 1, 5, 0, 1)
insert into ATRIBUTI values ('PRIMER', 'NM', 'NM_NAZIV', 'Naziv', 'varchar', 1, 128, 0, 0)
insert into ATRIBUTI values ('PRIMER', 'NM', 'NM_STAN', 'Broj stanovnika', 'decimal', 0, 0, 0, 0)
insert into ATRIBUTI values ('PRIMER', 'NM', 'NM_GRAD', 'Grad', 'bit', 0, 0, 0, 0)
INSERT INTO STRANI_KLJUC VALUES ('PRIMER','DRZ','PRIMER','NM','PRIPADA','Pripada',1,1,0,0)
INSERT INTO STRANI_KLJUC VALUES ('PRIMER','NM','PRIMER','DRZ','GLAVNI_GRAD2','Glavni Grad',0,0,0,0)
INSERT INTO STRANI_KLJUC VALUES ('PRIMER','NM','PRIMER','STU','RODJENJE','Rodjenje',0,0,0,0)
INSERT INTO STRANI_KLJUC VALUES ('PRIMER','NM','PRIMER','STU','STANOVANJE','Stanovanje',0,0,0,0)
INSERT INTO KOLONE_U_STRANOM_KLJUCU VALUES ('PRIMER','DRZ','PRIMER','NM','PRIPADA','DRZ_ID','DRZ_ID')
INSERT INTO KOLONE_U_STRANOM_KLJUCU VALUES ('PRIMER','NM','PRIMER','DRZ','GLAVNI_GRAD2','DRZ_ID','DRZ_ID_GG')
INSERT INTO KOLONE_U_STRANOM_KLJUCU VALUES ('PRIMER','NM','PRIMER','DRZ','GLAVNI_GRAD2','NM_PB','NM_PB')
INSERT INTO KOLONE_U_STRANOM_KLJUCU VALUES ('PRIMER','NM','PRIMER','STU','RODJENJE','DRZ_ID','STU_DRZRODJ')
INSERT INTO KOLONE_U_STRANOM_KLJUCU VALUES ('PRIMER','NM','PRIMER','STU','RODJENJE','NM_PB','STU_MESTORODJ')
INSERT INTO KOLONE_U_STRANOM_KLJUCU VALUES ('PRIMER','NM','PRIMER','STU','STANOVANJE','DRZ_ID','STU_DRZSTAN')
INSERT INTO KOLONE_U_STRANOM_KLJUCU VALUES ('PRIMER','NM','PRIMER','STU','STANOVANJE','NM_PB','STU_MESTOSTAN')
